### ISSUE TITLE
Ability to cache already initialized ViewControllers

### ISSUE THREAD

**Issue by mblcdr** [uias/Pageboy#124] opened 2017-12-03 17:32 UTC
Every time I scroll to a new tab, the `ViewController` is initialized (`viewController(for pageboyViewController at index)` is called), even if I were on that tab before. Shouldn't there be an option to cache already initialized `ViewControllers`?
Or we should store a map of already initialized `ViewControllers`?

**Comment by msaps** [comment] 2017-12-04 10:09
@mblcdr I think the expected behaviour is that you would manage the map of view controllers to provide to the PageboyViewController`, the way that the data source functions are designed is that they call `viewController(for: at:)` multiple times and expect a previously initialised view controller. 

The data source in v1.x previously did have the behaviour where you would initialise the view controllers in the data source function and it would only be called once. However this was pretty restrictive for re-use and configurations.

**Comment by mblcdr** [comment] 2017-12-04 10:26
Yes, I am familiar with the way that data source was implemented in v1.x. What I am trying to get at here is to have a caching functionality in the PageBoy to cache pages which are already initialized not all of ViewControllers as in v1.x). This feature can be disabled by default.
Alternatively, maybe something like a feature to specify how many pages should be kept in memory.
What are your thoughts on these?

**Comment by salvasp** [comment] 2018-02-10 17:03
I tried various approaches. The array "let pageControllers: [UIViewController]" of the example initializes all the children at begins taking time and memory (Especially for complex children and the children are a fixed number),
NSCache works but is a variable added (like pageControllers).
I was using like the example but "let pageControllers: [UIViewController?]" and set all to nil then 
in the "viewController for pageboyViewController" i check if is nil (I create and assign to the array) a new child else i return the one in the array (very similar to NSCache)

I also tried inside viewController for pageboyViewController to call 
pageboyViewController.viewController(at: index) and check id is nil to create or reuse but the app crashes (probably because I'm calling the function inside itself)

My last attempt is this piece of code inside "viewController for pageboyViewController"
I use the viewControllerMap variable as cache
```
guard let currentChild = pageboyViewController.viewControllerMap.object(for: index)?.object else {
            print("init \(index)")
            let viewController = UIStoryboard(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "ChildVC") as! ChildVC
            //viewController.collectionType = contrTypes[index] //my controller
            //viewController.delegate = self //configurations
            return viewController
        }
        print("reuse \(index)")
        return currentChild
```
This way I don't use extra variables and seems to work (but init is called pretty often)

What do you say? Is it a good approach?

**Comment by msaps** [comment] 2018-07-19 11:02
Going to close - the way that view controllers are managed/cached is the responsibility of the application providing them to the `PageboyViewController`.

**Closed by msaps** 2018-07-19 11:02 UTC
